### ISSUE TITLE
Chinese language text with multiple errors due to MACHINE-TRANSLATED

### ISSUE THREAD

**Issue by YakoseKumin** [immortius/chunkbychunk#103]
**Thank you for your willingness** to provide module translations for Chinese-speaking players.
However, in the last translation that was adopted, there were **many strange errors** due to the use of **machine translation**.
In order to make the mod spread better and let Chinese players feel your love for Minecraft, 
I have corrected and modified the original translation.
I found that I couldn't upload the file, so I had to add a link here↓
https://github.com/YakoseKumin/Localization/blob/main/zh_cn.json

_Thanks for your help. I hope I didn't disturb you.
With best wishes for a happy New Year!_

**Comment by immortius** [comment]
Addressed in 2.2.0
