### ISSUE TITLE
The current Chinese translation is machine translation, with a lot of errors

### ISSUE THREAD

**Issue by yizexiaomu** [immortius/chunkbychunk#105]
The current Chinese translation is very strange, to the extent that players playing in Chinese cannot understand the game content. Therefore, I have configured the Chinese text file myself
Hope you can adopt it! I will continue to follow up on the updated translation content in future versions as well
Anyway, happy New Year and all the best
[zh_cn.json](https://github.com/immortius/chunkbychunk/files/13858299/zh_cn.json)

**Comment by immortius** [comment]
Addressed in 2.2.0
