### ISSUE TITLE
Translations with Weblate.

### ISSUE THREAD

**Issue by peaceshi** [immortius/chunkbychunk#106]
https://hosted.weblate.org/projects/chunk-by-chunk/chunk-by-chunk-cn/

**Comment by peaceshi** [comment]
translation finished.
<a href="https://hosted.weblate.org/engage/chunk-by-chunk/-/zh_Hans/">
<img src="https://hosted.weblate.org/widget/chunk-by-chunk/chunk-by-chunk-cn/zh_Hans/svg-badge.svg" alt="翻译状态" />
</a>

**Comment by immortius** [comment]
Addressed in 2.2.0
