### ISSUE TITLE
Add a better chest random.

### ISSUE THREAD

**Issue by peaceshi** [immortius/chunkbychunk#107]

**Comment by immortius** [comment]
Added in 2.2.0

**Comment by Melechtna** [comment]
> Added in 2.2.0

Could you backport this to 1.19.2? The older chest method kinda....not as interesting tbh. Otherwise if you could maybe give me an idea of what to shove into kubejs to get a similar effect, I'd appreciate it.

**Comment by immortius** [comment]
I could, I guess mods didn't generally migrate to 1.19.4? -__-

**Comment by Melechtna** [comment]
> I could, I guess mods didn't generally migrate to 1.19.4? -__-

They really didn't, I've been stuck in 1.19.2 for most of my modpacks, and I built one around this as the core challenge, but then suddenly realized it's like...10ish versions behind, which, this is frankly miles better than skyblock, which my friends hate, so I was genuienly saddened when I realized. This is honestly one of the coolest "mod modes".

**Comment by immortius** [comment]
Ok, I'll upload a 1.19.2 variant in the next day or two. :)

**Comment by immortius** [comment]
Done, is available on modrinth and should appear on Curseforge shortly.

**Comment by Melechtna** [comment]
> Done, is available on modrinth and should appear on Curseforge shortly.

https://www.youtube.com/watch?v=gznDFlYHpb0
