### ISSUE TITLE
Heavy Lag with more alot of content mods

### ISSUE THREAD

**Issue by Joshernoob** [immortius/chunkbychunk#11]
I noted that this mod Forces its changes before world are made but its creates heavy lag as forge is required to load all the "data packs" of all mods in said pack before it can even get to the world create screen basicly mean loading all the mods twice, to use one mod.

I'd recommend making this more opimised or having a preset world type instead of injecting into the base world type

Example: I currently am using this mod in a modpack (beta) with the intent of it being the main world type mod (Modpack name: Chunk Block) currently in this pack iv had to cut corners to make a pack that should be light and usable by most pc into a pack that only mid-high end pc could handle by just adding one mod

**Comment by immortius** [comment]
I'll have a look and see if I can work out why that is happening.
I did originally use world presets but they don't always allow compatibility with other mods and it limits the ability to combine with the world types of other mods. Plus I don't think you can have a world preset that changes up the nether.

**Comment by immortius** [comment]
I tried out your mod pack and could see it takes a long time to load the world create screen. But this also occurred with Chunk By Chunk removed from the pack.

**Comment by Joshernoob** [comment]
Hmm, Ok for me it goes away when this mods removed so may be that different mod will have testers try removing this mod from pack and see if any show up and will inform here if they get same or different info

**Comment by immortius** [comment]
I'll also keep testing on my end. I am running the mod pack through MultiMC manually because it wouldn't even start via curseforge launcher.

**Comment by immortius** [comment]
I think I should also clarify - while Chunk By Chunk does apply its changes before world generation, it still does it after "server" creation - so it shouldn't be doing anything before the final Create New World button is clicked. Delays before reaching the world create screen shouldn't be caused by Chunk By Chunk unless another mod is inducing an early world creation for some reason.

**Comment by immortius** [comment]
Unable to reproduce
