### ISSUE TITLE
Bedrock terrain generation in stead of void around initial chunk

### ISSUE THREAD

**Issue by arthurjeremypearson** [immortius/chunkbychunk#111]
When generating a new world, terrain would spawn around the initial chunk as bedrock blocks, in stead of void.

**Comment by arthurjeremypearson** [comment]
apparently there are configs that change this

**Comment by WerQ346** [comment]
Hello, I really liked your mod and I want to play with it, but the bedrock texture is very strange for my taste. Is it possible to switch to another block? For example barriers

> очевидно, есть конфигурации, которые изменяют это

**Comment by WerQ346** [comment]
> apparently there are configs that change this

Hello, I really liked your mod and I want to play with it, but the bedrock texture is very strange for my taste. Is it possible to switch to another block? For example barriers

**Comment by immortius** [comment]
I guess your options are:
1. Disable sealed world in config, so there is air instead.
2. Create a data pack that changes the overworld sky dimension to use a different block for the seal (see https://github.com/immortius/chunkbychunk/wiki/Sky-Dimension-Data).
3. Create an asset pack that changes the bedrock texture to something more aesthetically pleasing.

**Comment by WerQ346** [comment]
Thank you very much!! You saved my eyes from this texture :) Thanks again!

> Я предполагаю, что ваши варианты следующие:
> 
> 1. Отключите sealed world в конфигурации, чтобы вместо него был air.
> 2. Создайте пакет данных, который изменит измерение неба над миром, чтобы использовать другой блок для печати (см. https://github.com/immortius/chunkbychunk/wiki/Sky-Dimension-Data).
> 3. Создайте пакет ресурсов, который изменит текстуру коренных пород на что-то более эстетичное.
