### ISSUE TITLE
WorldForge Recipes

### ISSUE THREAD

**Issue by WerQ346** [immortius/chunkbychunk#112]
Hello, how do I change a recipe in World Forge To delete recipes in it? In which file are the recipes for forge written inside the mod? I create a modpack strictly for personal play with a friend, not for distribution

**Comment by immortius** [comment]
To make sure we're not having an [XY Problem](https://en.wikipedia.org/wiki/XY_problem) perhaps best if you can share what you are trying to achieve.

The World Forge doesn't use recipes. Instead there are a number of configuration settings affecting its behaviour, primarily fuel value from soils, stones and "stronger sources" (if any are defined by a modpack), and fuel cost to make a fragment.  Tags are then used to set which items count as soils, stones, or stronger sources. If you are looking to remove items from soils and stones lists, you can replace the [weakworldforgefuel.json](https://github.com/immortius/chunkbychunk/blob/master/Common/src/main/resources/data/chunkbychunk/tags/items/weakworldforgefuel.json) and [worldforgefuel.json](https://github.com/immortius/chunkbychunk/blob/master/Common/src/main/resources/data/chunkbychunk/tags/items/worldforgefuel.json) tag files with empty ones using a datapack.

Modpack distribution isn't a problem regardless btw.

**Comment by WerQ346** [comment]
Thank you very much! Yes, you have clearly understood my question and solved it) I don't really know how distributions work in Curse and so on. Therefore, I do not risk it, because every mod has a license... btw thanks again for your help

> To make sure we're not having an [XY Problem](https://en.wikipedia.org/wiki/XY_problem) perhaps best if you can share what you are trying to achieve.
> 
> The World Forge doesn't use recipes. Instead there are a number of configuration settings affecting its behaviour, primarily fuel value from soils, stones and "stronger sources" (if any are defined by a modpack), and fuel cost to make a fragment. Tags are then used to set which items count as soils, stones, or stronger sources. If you are looking to remove items from soils and stones lists, you can replace the [weakworldforgefuel.json](https://github.com/immortius/chunkbychunk/blob/master/Common/src/main/resources/data/chunkbychunk/tags/items/weakworldforgefuel.json) and [worldforgefuel.json](https://github.com/immortius/chunkbychunk/blob/master/Common/src/main/resources/data/chunkbychunk/tags/items/worldforgefuel.json) tag files with empty ones using a datapack.
> 
> Modpack distribution isn't a problem regardless btw.
