### ISSUE TITLE
[2.2.1] Crash on initialization

### ISSUE THREAD

**Issue by ghost** [immortius/chunkbychunk#115]
Forge 40.2.17
Minecraft 1.18.2
*No good idea what causes this, but crashes during initialization with a mixin error.*
Log (includes mod list): https://mclo.gs/buyVULb

**Comment by ghost** [comment]
Even after disabling every mod, the crash still occurs. Same error.

**Comment by ghost** [comment]
> Even after disabling every mod, the crash still occurs. Same error.

Doesn't happen in version 2.2.0

**Comment by immortius** [comment]
Fixed in 2.2.2. I have an build issue affecting only Forge (1.18.2?) where sometimes it doesn't include all the mixin files in the final build. I re-released with all files included.
