### ISSUE TITLE
生成基岩宝箱时mc崩溃

### ISSUE THREAD

**Issue by xingchen-Forever** [immortius/chunkbychunk#116]
启用基岩补给箱会导致崩溃或者生成原版世界
mc版本：1.20.1
fabric加载器版本：0.15.6
fabricAPI版本：0.91.1
mod版本：2.2.0
mod配置为默认配置+启用基岩补给箱
仅安装fabricAPI和本mod
崩溃日志：如下
[crash-2024-02-12_11.53.37-server.txt](https://github.com/immortius/chunkbychunk/files/14235521/crash-2024-02-12_11.53.37-server.txt)

**Comment by immortius** [comment]
Got it. This will only happen with the randomised content selected, because it may attempt to add more than one item into the bedrock chest, and the bedrock chest only holds one item. I will expand the bedrock chest size.

**Comment by immortius** [comment]
Fixed in 2.2.3
