### ISSUE TITLE
World Scanner Ticking Block Entity Not Allowing Server To Run!

### ISSUE THREAD

**Issue by Woopagadon17** [immortius/chunkbychunk#12]
Hello There!  I placed a World Scanner block and suddenly my server crashed?  Added not enough crashes and Erroring Entity Remover and nothing changed.  I currently am not able to log in because the server crashes whenever I launch it!

Not sure if this is anything I can fix on my end or if I need to start a new world or...?
Any help is greatly appreciated! Thanks in advance! 👍 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/13/22, 4:37 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8497(int, int)" because "scanLevel" is null
	at xyz.immortius.chunkbychunk.common.blockEntities.WorldScannerBlockEntity.serverTick(WorldScannerBlockEntity.java:208)
	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk:659)
	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk:713)
	at net.minecraft.world.World.tickBlockEntities(World:475)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:368)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at xyz.immortius.chunkbychunk.common.blockEntities.WorldScannerBlockEntity.serverTick(WorldScannerBlockEntity.java:208)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)

-- Block entity being ticked --
Details:
	Name: chunkbychunk:worldscannerentity // xyz.immortius.chunkbychunk.common.blockEntities.WorldScannerBlockEntity
	Block: Block{chunkbychunk:worldscanner}
	Block location: World: (8,61,-27), Section: (at 8,13,5 in 0,3,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{chunkbychunk:worldscanner}
	Block location: World: (8,61,-27), Section: (at 8,13,5 in 0,3,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block Entity NBT: {ChargedFuel:32,Items:[{Count:1b,Slot:0b,id:"minecraft:raw_iron"},{Count:1b,Slot:1b,id:"chunkbychunk:worldfragment"}],Map:0,RemainingFuel:30,ScanCharge:34,ScanIterator:{Direction:0,LineLength:1,LineRemaining:1,X:15,Y:15}}
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,66,-24), Section: (at 8,2,8 in 0,4,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 280169 game time, 280169 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 101782 (now: false), thunder time: 2558 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2197813248 bytes (2095 MiB) / 5322571776 bytes (5076 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6589
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22985.48
	Virtual memory used (MB): 17626.65
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 516.78
	JVM Flags: 1 total; -Xmx6G
	Fabric Mods: 
		alternate-current: Alternate Current 1.4.0
		architectury: Architectury 4.5.76
		bclib: BCLib 1.4.7
		betterthanmending: BetterThanMending 1.3.0
		chunkbychunk: Chunk By Chunk 1.8.1+1.18.2
		connected-doors: Connected Doors 1.1+1.18
		consistency_plus: Consistency Plus 0.5.0+1.18.2
			stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		cosmetic-armor: Cosmetic Armor 1.3.1
		cpm: Customizable Player Models 0.4.3a
		eer: Erroring Entity Remover 1.0.2+1.18
		enchantmentcompat: Enchantment Compatibility 1.0.0
			roundalib: RoundaLib 0.1.8
		enderscape: Enderscape 0.3.3-1.18.2
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.3
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.3
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.3+kotlin.1.6.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.20
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.8
		horsebuff: HorseBuff 2.0.1
			cloth-config: Cloth Config v6 6.2.62
				cloth-basic-math: cloth-basic-math 0.6.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lithium: Lithium 0.7.10
		mcxr-core: [MCXR] Core 0.2.1
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			org_joml_joml: joml 1.10.4
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		minecraft: Minecraft 1.18.2
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				cardinal-components-base: Cardinal Components API (base) 4.1.4
				cardinal-components-entity: Cardinal Components API (entities) 4.1.4
				playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		purpeille: Purpeille 2.3.2+fabric-1.18.2
			cmods: Combined Modifiers 1.2.0
			voidcrafting: Void Crafting 1.6.4+fabric-1.18.2
		roughlyenoughitems: Roughly Enough Items 8.3.510
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		sky: Sky Origin 0.2.4
		starlight: Starlight 1.0.2+fabric.89b8d9f
		taxfreelevels: Tax Free Levels 1.3
		the_beginning: The Beginning 1.0.0
		toolleveling: ToolLeveling+ 1.18.2 - 1.3.3
		trinkets: Trinkets 3.3.1
		waystones: Waystones 2.5.5+mc1.18.2
		xaerominimap: Xaero's Minimap 22.11.1
		xaeroworldmap: Xaero's World Map 1.25.1
	Server Running: true
	Player Count: 0 / 10; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Chunk By Chunk (chunkbychunk)

**Comment by Woopagadon17** [comment]
It also works completely fine in Singleplayer!  Just figured I'd add that as I forgot to mention that!

**Comment by immortius** [comment]
Fixed in 1.8.3 for fabric + 1.18.2
