### ISSUE TITLE
[Fabric] [1.19] World Creation Crash

### ISSUE THREAD

**Issue by DubiousPhoenix** [immortius/chunkbychunk#13]
Hey there. I've been tinkering around with this and disabling almost all of my worldgen & structure mods (Dungeon Now Loading, Oh the Biomes You'll Go, etc) but I'm still having issues getting a world to generate. Here's the [Crashy](https://crashy.net/JGLTR6pP0Dyx7putakVS)

And I've attached the full crash log as well.
[crash-2022-07-16_18.41.41-server.txt](https://github.com/immortius/chunkbychunk/files/9126708/crash-2022-07-16_18.41.41-server.txt)

**Comment by immortius** [comment]
This looks to be the same issue as #7 - you might have your min chunk chest spawn height set greater than the max chunk spawn height.

**Comment by DubiousPhoenix** [comment]
Thanks for the fast reply. Hit the nail on the head. The max chunk depth was like -34 and the min was 12. Not sure why it was like that but after tweaking it the world generates just fine. Even with those structure mods put back in. Thanks for the help :)
