### ISSUE TITLE
EoF Exception - New chunks doesn't generate

### ISSUE THREAD

**Issue by Proxwian** [immortius/chunkbychunk#131]
Hello! Very love your mod and I made a modpack + server on it, but I faced a big issue with server today: new chunks suddenly stop generating (even after place ChunkGenerator and hear the beep from it after RMB click). So world with ~1 month history is unplayable now. Any thoughts what can cause this? Logs attached

![image](https://github.com/user-attachments/assets/057bcc6c-3858-4faa-a3e1-b9f415c82387)

**Comment by immortius** [comment]
Sounds like the chunkspawncontroller.dat file might be corrupted - should be safe to just delete it (can be found in the world/data directory). As to why... server might have shut down while it was in the middle of being saved or something? Not sure. Assuming the EOF exception is for that, it isn't really clear.
