### ISSUE TITLE
1.19.2 - 1.18.2 Players start away from each other on login and they have seperate world spawn points.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [immortius/chunkbychunk#19]
I Actually love this mod but it being the overworld ... is nightmarish for MP. I mean you could solve this in different ways including randomly placing each sign in somewhere else but the simple solution is just make a dimension. Anyways coolest skyblock ever and I hope you expand on this!

**Comment by immortius** [comment]
Mmm, I guess you are thinking in terms of an open server MP situation? I could see giving each player their own chunk on login, and possibly locking edits in a chunk to the person/party who placed it... but I'ld need to be careful not to do something that means players would never encounter each other. I probably need a better sense of what specific issues might crop up that aren't general minecraft MP issues. 

I did experiment with having the skyblock dimension not the overworld originally, and copying chunks from the overworld. The main issue there is just that there are some behaviors largely baked into minecraft that are difficult to reproduce in additional dimensions - beds skipping night and nether portals were examples.

**Comment by P3rf3ctXZer0** [comment]
... Hm what about option two each person that logs in is at least a set number of chunks away with land mass and trees of course.

**Comment by P3rf3ctXZer0** [comment]
I am now awake 🗡️

**Comment by immortius** [comment]
I think... the easiest approach would be just to used the sealed world variant and start each player with a forest chunk spawner and a bed, then they can find their own starting chunk. The forest chunk spawner just helps guarantee they start with some trees on their chunk.

I guess fair warning it will probably be a while before I get around at looking at this proper. I plan to backport the latest version to 1.18 first, and I have some other projects that need attention.

**Comment by P3rf3ctXZer0** [comment]
Sounds good I look forward to the future then.

**Comment by immortius** [comment]
Closing this. The suggested technique with using a sealed world and starting each player with a chunk spawner should be doable as is - I'm sure there are existing mods to customise starting loadouts of players. So not clear what change I would make as part of this issue.
