### ISSUE TITLE
1.19.2 - Fails to start game with IC2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [immortius/chunkbychunk#22]
Forge Version: 43.1.47
Mod: ChunkByChunk-forge-1.19.2-1.9.0

Crashlog
https://gist.github.com/P3rf3ctXZer0/84d1aa6fd38ba668f52605e53cc7aab2

![y1tfHZf 1](https://user-images.githubusercontent.com/10351221/198834804-af0cf359-db44-44b8-b7c6-3537fd97d08c.png)

**Comment by immortius** [comment]
I was unable to reproduce running just ChunkByChunk and IC2-Classic (and forge 43.1.47). Are you sure the issue isn't with another mod in your list? What is the minimum set of mods that exhibits the crash?

**Comment by P3rf3ctXZer0** [comment]
I only test with my modpack environment as I don't have time for individual testing you could grab this.

https://www.curseforge.com/minecraft/modpacks/fiction-friction 23.0.0

**Comment by P3rf3ctXZer0** [comment]
If you look at the modpack you could try adding all mods to a test environment that add fluids.

**Comment by immortius** [comment]
I narrowed it down to ChunkByChunk + IC2-Classic + Mekanism.

**Comment by P3rf3ctXZer0** [comment]
Awesome. Sorry I have been exhausted I pulled a 32 hour shift at the time of posting with only about 12 hours sleep between.

**Comment by immortius** [comment]
I've worked out what was going on and have a fix for it, will include in next version.
