### ISSUE TITLE
1.19.2 Not smart enough for data packs can you provide a template

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [immortius/chunkbychunk#29]
Yea sorry I am too stupid for data packs that solution is not a solution for me. I have tried hard to learn them but I am just too dumb.

**Comment by immortius** [comment]
I certainly should created some documentation at least.
In the meantime the definitions for the overworld + nether may be used as examples (https://github.com/immortius/chunkbychunk/tree/master/Common/src/main/resources/data/chunkbychunk/skydimensions)
and there is a description of the format in the original issue: https://github.com/immortius/chunkbychunk/issues/21#issuecomment-1306497204

I haven't actually developed a modpack/datapack before so I cannot be of a lot of assistance in that space currently, but I believe beyond the standard datapack setup you would add a folder structure with data/<packname>/skydimensions/ containing the data files for each dimension you want to be a sky dimension, and that _should_ work.
