### ISSUE TITLE
Nether chunks

### ISSUE THREAD

**Issue by SylisMC** [immortius/chunkbychunk#3]
If there isn't a way to do this already, could you add the same generation for the nether?

It would be really cool if the nether chunks were bound to the overworld chunks, the dimensional scale would have to be reset to 1-1 or have a hellforge for meaning nether chunk spawners

**Comment by immortius** [comment]
I could replicate a similar setup for the nether, although I'ld want to do something different about empty chunks - they'll all need bedrock ceilings and possibly a layer of lava at the bottom.

**Comment by SylisMC** [comment]
oooooo i can picture it now... that sounds awesome.

**Comment by immortius** [comment]
I ended up having nether spawn in tandem with overworld chunks... but maintaining dimensional scale so you have to spawn overworld chunks 8 apart to get more nether.
