### ISSUE TITLE
Request: Command to force spawn chunks

### ISSUE THREAD

**Issue by SylisMC** [immortius/chunkbychunk#4]
Hey, I've been playing around with this mod for a few days now, and I've started creating a premade world for playing chunk by chunk as a multiplayer team effort for a group of my friends. But the project is turning out to be a lotta fun to make and I think others would get enjoyment out of it aswell.

If you would be willing to add a way for users to force spawn in chunks via command, I could try to edit this world into a datapack to allow people to generate their own worlds with random seeds and have it automatically spawn in the chains and other islands. 

Thanks for considering my request :)

![2022-04-03_10 50 09](https://user-images.githubusercontent.com/19602662/161434024-616a1552-06cb-453b-bfeb-50dfd81c85c8.png)
![2022-04-03_10 50 23](https://user-images.githubusercontent.com/19602662/161434025-abb45aed-ed56-4464-baa7-ef056182b74f.png)
![2022-04-03_10 51 03](https://user-images.githubusercontent.com/19602662/161434026-d0b150f2-83d0-4522-b71f-bb18632a276d.png)
![2022-04-03_10 51 33](https://user-images.githubusercontent.com/19602662/161434028-1711f6ba-53f5-4668-bd3f-609724fe135e.png)

**Comment by immortius** [comment]
It is a fair request. Technically, there is a slight issue to resolve - it takes a little time between making a generation dimension chunk relevant, and its entities being available to copy. For the chunk spawn block this is resolved by having the block placement bring the chunk into relevance, and then activation do the copy. I guess I could make a command that spawns an invisible block that then waits a tick and activates, that would fix it.

**Comment by immortius** [comment]
I guess for your purpose, is it a problem that the initial chunk isn't always 0,0 (ChunkByChunk searches for one with reasonable starting conditions)?

**Comment by SylisMC** [comment]
It would probably be a lot easier if 0,0 was always spawn, but it's not critical I should be able to find ways around it. maybe by scanning the bedrock on the chunk to identify where the corner of the chunk is. it should all just be math from there. as long as I can find a way to determine a baseline that is always consistent. 

Perhapse adding a block state to the chunkspawner would be the easiest way to make spawning chunks with a command possible?, a player could use setblock as following
```/setblock [x] [y] [z] chunkbychunk:chunkspawner[active=true]```

**Comment by immortius** [comment]
I've added ```chunkbychunk:spawnChunk [location]``` and ```chunkbychunk:spawnRandomChunk [location]``` commands in 1.7.0.

Similar to your suggestion I've added extra invisible blocks that run the chunk spawning process as well, but recommend using the commands because they do the majority of the spawning immediately. Also shields from future changes.
