### ISSUE TITLE
Feature request: Portal to and from overworld dimension

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#41]
Currently, there is a command to teleport to the undamaged overworld and back to chunk by chunk. I would love to see a feature to either build a portal or use an item to do that without cheating. In modpacks using storylines, this could be a cool addition. As of now, Waystone Mod does work to teleport within a dimension, but it doesn't let you use the same waystone to switch dimensions, because it shares the same ID (I think). 
As far as I understand how Chunk by Chunk works, you could *in theory* have one self-built building in the petrified world (for example) and not in the original one, correct? This would be a cool way to add more options to how you play between those chunks. 
Maybe the item/portal for dimension switching is expensive and you have to grind quite a lot at first, or the like. This would encourage to keep going, maybe. There could also be a config option to have some things not be copied from the original world so you have a clear desire to go back to that world. 
That's my idea. Thanks for reading!

**Comment by immortius** [comment]
Won't be doing this, as it is a gateway to item duplication (go to the generation dimension, place blocks/items in an not-yet-spawned chunk, spawn it, retrieve items). :)
