### ISSUE TITLE
Resetting issue with Nether chunks.

### ISSUE THREAD

**Issue by FrozenDragon0** [immortius/chunkbychunk#46]
Okay, so I'm not 100% sure what is causing this but I have noticed that on rare occasions parts of my nether chunk seems to just mysteriously reset itself for no apparent reason.

I noticed this again as I had dug out a staircase down to Y level 15 to search for Netherite and I've come back on the world again to find that all the Netherrack I had dug out has been completely reset back to it's original state, as if I had never even touched it.

This is the area I had dug out previously and it has been mysteriously reset on it's own. Yet other modifications I've made in the chunk have been left as is.
![2023-01-18_21 58 59](https://user-images.githubusercontent.com/18079316/213190546-848511e5-fb3e-46eb-972c-50c4d8f1b8b8.png)

Mod version is the latest BTW, 1.12.0 with Sync Nether chunks enabled.

**Comment by FrozenDragon0** [comment]
> Can confirm there seem to be some issues, probably specifically with the 1.18.2 backport of 1.12.0. I'll try and get that fixed up as a priority.

I have had this occur on 1.19.2 aswell IIRC, also off-topic but how does the Nether chunk syncing work exactly? A bit confused as to how the mod knows when to generate a Nether chunk once the requirement is met in the Overworld.

**Comment by immortius** [comment]
Basically whenever you spawn a chunk in the overworld, the equivalent chunk in the nether (taking into account dimensional scaling) is spawned if it hasn't been already.

This seems to be working fine, the issue appears to be with saving/loading the nether dimension.

**Comment by immortius** [comment]
Fixed, thank you for the heads up.

**Comment by FrozenDragon0** [comment]
Awesome!

**Comment by FrozenDragon0** [comment]
> Basically whenever you spawn a chunk in the overworld, the equivalent chunk in the nether (taking into account dimensional scaling) is spawned if it hasn't been already.
> 
> This seems to be working fine, the issue appears to be with saving/loading the nether dimension.

It seems that this is not 100% fixed, while blocks I have placed no longer get erased, any blocks I've dug out in the Nether seem to have been reset as if I never dug any blocks there in the first place.

Mod version used is 1.20.1 2.2.3
