### ISSUE TITLE
Chunkbychunk on forge1.19.3 instantly crashes

### ISSUE THREAD

**Issue by LavaDogX** [immortius/chunkbychunk#48]
Chunkbychunk will instantly crashes on forge 1.19.3. Have created new instances and it causes Minecraft to not even start.

**Comment by immortius** [comment]
Thank you for the heads up, looks like all the forge builds have been broken since I migrated to 1.19.3 - but only the final builds, not the builds I was testing with :/

I've fixed this in 1.12.2
