### ISSUE TITLE
Slime Chunks Suggestion?

### ISSUE THREAD

**Issue by Afrocntrik** [immortius/chunkbychunk#5]
Implementation for using a slime chunk generator either through a Slime Chunk Spawner block?
Possible world scanner slime chunk finder?

**Comment by immortius** [comment]
Mmm, I'll have to have a bit of a look how things are currently behaving. In principle slink chunks are where they always would be, just need to spawn them. 

Adding scanning for a slime chunk is a good idea, but is requiring you to have some slime to find one reasonable?
