### ISSUE TITLE
[Suggestion] Various Suggestions

### ISSUE THREAD

**Issue by TheonlyTazz** [immortius/chunkbychunk#50]
### KubeJS Integration

What would be amazing to see is having a way to increase the chunks around the original players spawn chunk via KubeJS
Also in addition to this, it would be amazing to make the Biomespawners moremodular and be able to get biomes from other Dimensions or even other Mods (have a biomeSpawner block, that has a biome Tag, which then initiate the biome generation)
this would make the block way more versatile

### Bind Players/Teams to a spawnchunk

For Multiplayer purposes it would be good to have a spawn chunk be assigned to a player or a team, that way, multiple people can play in the same dimension

### More Configs

Make the Mender more customizable in terms of speed and the possibility to (in combination with the modular biomeSpawner) generate corosponding chunks dependant on the spawner that is fed

**Comment by immortius** [comment]
World mender spawn rate will be configurable in 2.0.0, and spawned chunk will be determined by chunk spawner provided.

**Comment by immortius** [comment]
Closing with the More Configs part done in 2.0.0. Bind Player/Teams to a spawnchunk will be covered by #76. Also split out #78 for KubeJS integration, although partially covered by the existence of spawn chunk commands.

Also I missed this originally, but the biome themed spawners are configurable per dimension via the sky dimension data packs (can map each themed spawner to a list of biomes, which can be from any dimension and mods (although results may vary).
