### ISSUE TITLE
Modpack Crash during game initialization 1.18.2 after latest CBC update

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#59]
Hi there! I just read you updated the mod to 1.13.0 so I went and tried it out... I mean, I tried trying it out, but the game crashes by doing so. 

It says something is trying to access a private field. Maybe you know what's happening?

My crash report: 
[crash-2023-02-19_13.13.38-client.txt](https://github.com/immortius/chunkbychunk/files/10776956/crash-2023-02-19_13.13.38-client.txt)
[latest.log](https://github.com/immortius/chunkbychunk/files/10776960/latest.log)

Forge 40.2.0

**Comment by immortius** [comment]
You appear to be running two versions of chunk by chunk

**Comment by xFirefalconx** [comment]
Ah, yes I found the duplicate. The error persists, sadly. New logs:

[crash-2023-02-19_15.31.22-client.txt](https://github.com/immortius/chunkbychunk/files/10777253/crash-2023-02-19_15.31.22-client.txt)
[latest.log](https://github.com/immortius/chunkbychunk/files/10777255/latest.log)

**Comment by immortius** [comment]
Unsure. Doesn't seem to be anything related to chunk by chunk in the logs. Just crashing in the minecraft renderer during first render. Does this happen for you with just Chunk By Chunk? What is the minimum set of mods that trigger the issue?

**Comment by xFirefalconx** [comment]
Alright, will let you know once I found the bunch that is responsible. Might take a while though. 

You might test if it's got anything to do with asticor carts, manyideas doors or sakurablossomgrotto. Those three were clowning around last time, but not sure if it's because of that. First of them got tons of bug reports last time I checked. I'll let you know once I found the time to single out CBC and see if it works or not.

**Comment by xFirefalconx** [comment]
Update. It is a combined bug. I can start CBC without the other mods. I will single out the clown now.

**Comment by xFirefalconx** [comment]
[05:48:29] [main/ERROR]: Unsupported installed optional dependencies:
	Mod ID: 'jei', Requested by: 'chunkbychunk', Expected range: '[10.2.1.1002,11)', Actual version: '9.7.1.255'
	
	Does that pose any issue?

**Comment by immortius** [comment]
Well, it won't run, but it shouldn't cause a crash.

**Comment by xFirefalconx** [comment]
Mod ID: 'jei', Requested by: 'moreoverlays', Expected range: '[9.7.0.229,10.0.0.0)', Actual version: '10.2.1.1002'


Unsure if this is the crash cause. I am contacting the author rn to find out what's going on. 
I halved the mods and both halves were working but with an overlap. I am testing said overlap in hope the error is between there somewhere.

**Comment by xFirefalconx** [comment]
Edited. Closing from my side.

**Comment by immortius** [comment]
Mmm. I kind of need to use a version 10+ of JEI, because that is when fabric support was added and thus allows me to continue to have the one code base for both mod loaders. There isn't a non-beta version of JEI in that space yet though.
