### ISSUE TITLE
[Suggestion] Add JEI 9 support

### ISSUE THREAD

**Issue by TheonlyTazz** [immortius/chunkbychunk#60]
### Mod Version
ChunkByChunk-forge-1.18.2-1.13.0.jar

### JEI Version
jei-1.18.2-9.7.2.1001.jar

---

![image](https://user-images.githubusercontent.com/3908847/221942596-ed2815b1-9987-4571-b14b-6a04d7ff694e.png)

I was just busy developing my modpack and got greeted with this.

I cannot use JEI 10, as alot of other mods that I am using dont support JEI 10...

would it be possible for you to add JEI 9 Support?

**Comment by immortius** [comment]
I will do a little research into it, at least in terms of seeing if chunkbychunk can not break in the presence of JEI 9. The main problem is JEI 10 was the first version with forge+fabric support from a common API, which is really useful as a project supporting both forge and fabric.

The ideal middle ground is probably Chunk By Chunk not having a dependency on JEI and not providing JEI integration with 9, but still supporting 10+

**Comment by immortius** [comment]
Released 1.13.1 for Forge 1.18.2 specifically, which allows the presence for JEI 9 (although it doesn't integrate with it).
