### ISSUE TITLE
Incompatibility with Serene Seasons

### ISSUE THREAD

**Issue by Insane96** [immortius/chunkbychunk#69]
Seems like they both change the grass / foliage color so they flicker

**Comment by immortius** [comment]
I gave this a whirl in 1.19.3 forge, and was unable to reproduce - so might need some more details. Chunk By Chunk doesn't directly change grass/foliage color, but it does alter biomes when it spawns chunks (as needed) which I imagine could cause issues.

**Comment by immortius** [comment]
Unable to reproduce, more information required.
