### ISSUE TITLE
Crashing on Worldgen - no bedrock chest

### ISSUE THREAD

**Issue by Naddox** [immortius/chunkbychunk#7]
Working on a modpack and just added your mod. Everytime I generate a new world the game crashes with the below crashlog. I can load the world after this crash but after verifying with 3 worlds and a xray mod, I have verified that the bedrock chest doesn't generate.

https://pastebin.com/FeTtMsyF

Getting this one when generating a new chunk with any chunk spawner
https://pastebin.com/6adZskQc

**Comment by immortius** [comment]
Hi @Naddox 

How have you configured the min and max spawn height for the chest (if it has been changed at all)?

I've only been able to reproduce the issue when max spawn height is < min spawn height. Which is still a bug on my end but at least can be worked around.

**Comment by Naddox** [comment]
Hey @immortius 
The first time I had the issue I had the min at -50 and max at -60 (however its possible I wasn't paying attention and did it backwards).

After that I had set it for both to -50 for testing the other worlds. I will delete the config and see if that is a workaround for me at least.

**Comment by Naddox** [comment]
> I will delete the config and see if that is a workaround for me at least.

This did fix the crash, however the bedrock chest still didn't spawn. Instead, a normal chest spawned with a world core inside.
