### ISSUE TITLE
Request: Add creative tab 1.18.2

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#70]
Hi, hope this is no duplicate. 
I've been clicking through my creative tabs as of late and noticed on 1.18.2 I couldn't get any CBC related one. I have no clue how difficult it would be to implement that, but it would save me some headache retrieving the items, if JEI and the search happen to act up (which they unfortunately sometimes do for me).

**Comment by immortius** [comment]
The CBC items are under the Misc tab (or should be)
