### ISSUE TITLE
1.18.2 issue when spawning chunks under snow layers

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#71]
![grafik](https://github.com/immortius/chunkbychunk/assets/106652912/f6834ce1-2687-4fe2-9701-8b5dcabd6de3)

I suppose that snow layers were no problem before, but as you can see, spawned in village pieces get sliced open. I'm using the better village mod. 

CBC ver: 1.13.4
bettervillage-forge-1.18.2-3.1.0

Forge 40.2.4
MC 1.18.2

I guess that snow is just not on the to be replaced list. I'm using Snow! Real Magic! as well, which adds snow, plus Serene Seasons but those are probably just partially involved here. 

(Would btw love to have a creative chunk spawner that redoes the spawning process when something has gone wrong, for debugging purposes, which only works when Player is in Creative mode. I know you're working on a redesign of the spawning process, but for such cases it would be a nice-to-have band-aid.)

Let me know if you need more info!

**Comment by immortius** [comment]
This is pretty clear, thank you, I hadn't thought about falling snow and how it would fall on sealed worlds specifically.

If you want to regenerate a chunk, you can replace the bottom layer of the chunk with air (that is what is checked to determine if a chunk has been spawned or not).

**Comment by xFirefalconx** [comment]
Alright, thanks for the info! And you're welcome :D 
Can you give me a heads up when the fix is roughly available?

**Comment by immortius** [comment]
Ah, well, I haven't been working on Chunk By Chunk recently... but I will certainly do a new version after 1.20 is out, so probably as part of that. May take a couple of weeks before that can be done though, as I'll be waiting for dependencies to release their updates. Will give me some time to experiment with performance improvements.

**Comment by immortius** [comment]
Fixed in 2.0.0
