### ISSUE TITLE
Feature request: special Serene Seasons / Snow! Real Magic! compat

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#72]
Serene seasons lets you have specific seasons while Snow real Magic adds snow layers during winter. 

I would love to have the petrified chunks set to be in winter (aka override their season - set to fit with the reference chunk, or set to a specific season as long as they're petrified. you could set them to winter, spring, summer, fall.)
Plus, when you have the season set to winter let newly generated petrified chunks be covered in a thin layer of snow. This makes for a great optional variation of surroundings, perfect for modpacks! 
I hope this is possible somehow.

**Comment by immortius** [comment]
In 2.0.0 I'm implementing support for overriding the biome of sealed chunks as well as set a "covering" block (there is already the ability to set what block is used to seal chunks) - this is part of the sky dimension data pack format rather than configuration though.
