### ISSUE TITLE
Server crashes after placing world mender in Nether and filling it with World Cores

### ISSUE THREAD

**Issue by Assaro** [immortius/chunkbychunk#74]
After doing the action described above my server keeps crashing. This is not the first time we have used the world mender in the Nether and we had no problems before. I suspect that it might have something to do with the fact that the Chunk it is sitting in is forceloaded, but i do not know if that causes it. I will attach a logfile for you and will report back if i find the error
[crash-2023-06-07_20.08.01-server.txt](https://github.com/immortius/chunkbychunk/files/11680638/crash-2023-06-07_20.08.01-server.txt)

**Comment by Assaro** [comment]
The error has not been fixed by removing the forceload on the chunks. I was able to fix it by removing the World Mender using a save Editor. If you need it i can supply you with the world file and the used mods

**Comment by immortius** [comment]
Thank you for your report. The world file would be useful, if you can provide it. Although I think I have an idea what to change to prevent the issue happening again. (It has to do with teleporting entities from the chunk generation dimension to the nether, my code isn't being aggressive enough in overriding minecraft's default code).

**Comment by Assaro** [comment]
File was too big for Github, so have a download link:
https://we.tl/t-Yw2gZi1RYP

**Comment by immortius** [comment]
Fixed in 2.0.0
