### ISSUE TITLE
Forge 1.20.1 - Can not leave starting biome blank in config - it isn't saved/loaded properly

### ISSUE THREAD

**Issue by Peach774** [immortius/chunkbychunk#80]
When setting the default config to a blank starting biome (nothing in the box), it doesn't save and must be changed every time you launch the game if you are going to make a world in the ingame mod menu. Disabling it in the mod menu appears to work.

**Comment by immortius** [comment]
Mmm, this is because if the value is blank or missing it gets set to the default value on startup. I'll add an extra setting to control if the default biome is used next version.

**Comment by immortius** [comment]
Addressed in 2.1.0
