### ISSUE TITLE
when i join my world, all the blocks I mined reappear

### ISSUE THREAD

**Issue by stunlocked1** [immortius/chunkbychunk#86]
https://gist.github.com/stunlocked1/59bf6338012644990f4242c72e20ebac

**Comment by stunlocked1** [comment]
> I guess some sort of mod incompatibility... Are you running a mod that makes the world floating islands or similar? Chunk By Chunk detects a chunk as spawned based on there being bedrock at the bottom, so if that isn't the case it will respawn chunks (and thus remove your changes).

i just noticed skulk paint thing at the bottom under bed rock could that be the issue

**Comment by immortius** [comment]
That... does seem curious. The only way you could have sculk at the bottom is if there is at least a layer of air/sculk below bedrock. Which would mess with Chunk By Chunk. Also you have water flowing below the bottom of the chunk too...

**Comment by stunlocked1** [comment]
so i updated all my mods and it fixed itself, whatever mod did this probably got fixed
