### ISSUE TITLE
1.18.2 + Regions Unexplored - Tall Saplings break on Chunk Spawn

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#88]
There's a strange behaviour when spawning chunks that include Tall Saplings of many kinds (found it to be happening to various kinds of maple and birch types), I don't know how much you can control that at all, and if there's a difference between world mender and manual chunk spawning, but the saplings break the moment they are spawned, emitting particles and then dropping themselves. 
No idea if there's a way to fix this on your side, but I thought I better report than not. 

Tested on my modpack, so if you cannot reproduce it, please let me know. 
Regions Unexplored 0.4.1 (try with Autumnal Maple Forest or Silver Birch Forest as a comparison (for me the silver birch saplings are fine, sometimes, but not always), for example)
CBC 2.1.0
Forge 40.2.10

Maybe it's an issue with how the saplings are derived/placed, idk. It's very inconsistent to me.

**Comment by immortius** [comment]
I assume this will be similar to how hanging snow/sand falls on chunk spawn as well - since spawning chunks places the blocks it triggers effects like that. Presumably the tall saplings see that they're only half there part way through the spawning and drop themselves.
