### ISSUE TITLE
[Feature Request] Nether Chunks

### ISSUE THREAD

**Issue by Darkosto** [immortius/chunkbychunk#9]
Hello!

I would love to use this mod in a future pack and I had a question/feature request. I want to set up Chunk by Chunk to spawn in new chunks via my Twitch Chat using Content Creator Integration. I'm a big fan of the random chunk placement. Is there any way I could pull in chunks from other dimensions? Also, could the nether also start as a void and have new chunks built independently from the Overworld?

Thanks for all of your hard work!
Darkosto

MC: 1.18.2
ChunkbyChunk: 1.8.2
Forge: 40.1.25

**Comment by immortius** [comment]
Cross dimension chunks are... troublesome. Not technically, but netherworld chunks are much shorter than overworld chunks, so it is difficult to pair them together. And the end has a lot of empty chunks.

Currently you can configure the Nether to start empty and spawn in synch with the overworld (so the nether-equivalent chunk of each overworld chunk will be present). This could be expanded to have the option of an empty netherworld that needs to be manually spawned which I think would meet your request.

**Comment by immortius** [comment]
This should be doable using the skydimension data pack support being introduced in 1.10.0
