### ISSUE TITLE
Suggestion: World Type

### ISSUE THREAD

**Issue by ChosenArchitect** [immortius/chunkbychunk#92]
I don't know how easy this would be to do but could it be possible to make this a World Type Option instead of default for every world generated? If so this would make it easier to add to modpack projects that might not want the entire modpack to start as a chunk world but have the option to do so. 
~Chosen :D

**Comment by immortius** [comment]
There are a few things in place for this currently. You can enable/disable the chunk by chunk generation as a mod config option, which then applies to worlds created. So a modpack could include a default config for Chunk by Chunk with world gen disabled.

Modpacks can also override and extend the sky dimension definitions if they want to turn on or off Chunk by Chunk for individual dimensions.

I did originally use world type, but it caused compatibility issues with other world gen affecting mods.

**Comment by dreckz** [comment]
Is there a way to select the dimension it seals?  I'm attempting to make another dimension sealed, and make the overworld pure @immortius
