### ISSUE TITLE
Ocean biomes can't be overwritted

### ISSUE THREAD

**Issue by jinkhya** [immortius/chunkbychunk#93]
Hello,
It seems that when you move to an ocean biome, place any biome chunk or even just chunk spawner it just spawns water like an ocean. I tried a few times with a desert chunk spawner and ended up with a 16x16 water chunk every time, even though my map says it's a desert.

I'm guessing it's because the mod replaces blocks with the ones from the desired biome? so if it's water it only replaces the blocks under the water?

Best regards,
Jin

**Comment by immortius** [comment]
Well, it's tricky. The mod replaces biomes, but the ocean biome isn't responsible for the surface level - surface level is generated before biomes are assigned (it is one of the factors minecraft uses when determining what biome to place in an area). So yes, if the area is going to be filled with water, it will be regardless of what spawner is used. I don't have a good solution for it.

The actual replacement is a little tricker than just swapping blocks - the mod generates a dimension that only contains relevant biomes for each spawner and copies from those. So effectively if you use a desert spawner you get the chunk from a world that is all desert biomes.
