### ISSUE TITLE
World Forge Crash

### ISSUE THREAD

**Issue by ChosenArchitect** [immortius/chunkbychunk#95]
This is in ref to cobble gen that will eventually cause a rendering crash in the World Forge.

Issue ref: https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/53

Crash Log Posted: https://mclo.gs/s6ysyKH

Minecraft version: 1.20.1
Forge Version: 47.1.3
Modpack ref: https://legacy.curseforge.com/minecraft/modpacks/chosens-modded-adventure-chunk-by-chunk

**Comment by immortius** [comment]
Fixed in 2.1.1
