### ISSUE TITLE
[1.18.2 ticking player] crash with SoulHome 

### ISSUE THREAD

**Issue by xFirefalconx** [immortius/chunkbychunk#98]
According to the info collected here it's a "already running this task" issue - I hope you know a way to resolve this? 
https://github.com/leafreynolds/soulhome/issues/5

I confirmed both mods crash together, the rest of the pack seems unaffected, after disabling CBC in a test profile and entering the SH dimension. 
Here's a copy of the crash log so you can look up what's going wrong. The SH dev also looked at the situation and gave hints in the linked github issue.
[crash-2023-11-15_20.26.49-server.txt](https://github.com/immortius/chunkbychunk/files/13369990/crash-2023-11-15_20.26.49-server.txt)

**Comment by xFirefalconx** [comment]
New information, the crash doesn't affect not petrified worlds (where I used the CBC config to spawn in the overworld, instead)
I could freely enter and leave the Soulhome dimension there.

**Comment by immortius** [comment]
Technical detail is something along the lines of:
* Soulhome or its dependencies unfreezes the dimension registry so it can later add dimensions as needed
* Chunk By Chunk unfreezes, inserts its dimensions and re-freezes the dimension registry on start up
* When you first use the soulhome key it tries to insert a new dimension into the dimension registry and fails

So fix is I just won't re-freeze the dimension registry (which I was doing to minimise impact on standard minecraft behavior).

**Comment by immortius** [comment]
Fixed in 2.1.1

**Comment by xFirefalconx** [comment]
Thanks a lot for your fix! I'll eagerly await the update 2.1.1 :)

**Comment by xFirefalconx** [comment]
Thanks a lot for your fix! I've successfully tested the update already!
